chore: Update

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -77,3 +77,10 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           fail_ci_if_error: true
+
+      - name: Check version equality
+        run: |
+          pattern="__version__ = \"$(poetry version --short)\""
+          if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
+            echo "::error::Version does not match __version__ variable."
+          fi
diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -51,6 +51,13 @@ jobs:
       # ------------------------------------------------------------------------
       # Publishing & draft release.
 
+      - name: Check version equality
+        run: |
+          pattern="__version__ = \"$(poetry version --short)\""
+          if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
+            echo "::error::Version does not match __version__ variable."
+          fi
+
       - name: Publish to TestPyPI with Poetry
         run: poetry publish --build -n -u __token__ -p "$TOKEN"
         env:
diff --git a/.github/workflows/testpypi.yaml b/.github/workflows/testpypi.yaml
--- a/.github/workflows/testpypi.yaml
+++ b/.github/workflows/testpypi.yaml
@@ -58,6 +58,19 @@ jobs:
         if:  ${{ inputs.version != '' }}
         run: poetry version -- ${{ inputs.version }}
 
+      - name: Adjust __version__ variable
+        if:  ${{ inputs.version != '' }}
+        run: |
+          pversion="$(poetry version --short)"
+          sed -i "/^__version__/c\__version__ = \"$pversion\"" src/*/__init__.py
+
+      - name: Check version equality
+        run: |
+          pattern="__version__ = \"$(poetry version --short)\""
+          if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
+            echo "::error::Version does not match __version__ variable."
+          fi
+
       - name: Configure Poetry repo for TestPyPI
         run: poetry config repositories.testpypi https://test.pypi.org/legacy/
 
