chore: Update

diff --git a/.github/workflows/testpypi.yaml b/.github/workflows/testpypi.yaml
--- a/.github/workflows/testpypi.yaml
+++ b/.github/workflows/testpypi.yaml
@@ -68,7 +68,7 @@ jobs:
         run: |
           pattern="__version__ = \"$(poetry version --short)\""
           if ! grep -q -R -F --include="__init__.py" "$pattern" src; then
-            echo "::error::Version does not match __version__ variable."
+            echo "::error::Version set with Poetry does not match __version__ variable."; exit 1
           fi
 
       - name: Configure Poetry repo for TestPyPI
